// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 1 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int fixedzerovalue_1 = 1;
	/// <summary>PID: 1 | Type: read</summary>
	public const int fixedzerovalue = 1;
	/// <summary>PID: 2 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int placeholdernotavailablevalue_2 = 2;
	/// <summary>PID: 2 | Type: read</summary>
	public const int placeholdernotavailablevalue = 2;
	/// <summary>PID: 1001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int devicemode_1001 = 1001;
	/// <summary>PID: 1001 | Type: read</summary>
	public const int devicemode = 1001;
	/// <summary>PID: 1003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encodercurrentcompressedbitrate_1003 = 1003;
	/// <summary>PID: 1003 | Type: read</summary>
	public const int encodercurrentcompressedbitrate = 1003;
	/// <summary>PID: 1004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int autochromaweight_1004 = 1004;
	/// <summary>PID: 1004 | Type: read</summary>
	public const int autochromaweight = 1004;
	/// <summary>PID: 1005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int chromaweight_1005 = 1005;
	/// <summary>PID: 1005 | Type: read</summary>
	public const int chromaweight = 1005;
	/// <summary>PID: 1006 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int losslessmode_1006 = 1006;
	/// <summary>PID: 1006 | Type: read</summary>
	public const int losslessmode = 1006;
	/// <summary>PID: 1007 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercurrentcompressedbitrate_1007 = 1007;
	/// <summary>PID: 1007 | Type: read</summary>
	public const int decodercurrentcompressedbitrate = 1007;
	/// <summary>PID: 1008 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int progressionorder_1008 = 1008;
	/// <summary>PID: 1008 | Type: read</summary>
	public const int progressionorder = 1008;
	/// <summary>PID: 1009 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockwidth_1009 = 1009;
	/// <summary>PID: 1009 | Type: read</summary>
	public const int codeblockwidth = 1009;
	/// <summary>PID: 1010 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockheight_1010 = 1010;
	/// <summary>PID: 1010 | Type: read</summary>
	public const int codeblockheight = 1010;
	/// <summary>PID: 1015 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int totalencodertx_1015 = 1015;
	/// <summary>PID: 1015 | Type: read</summary>
	public const int totalencodertx = 1015;
	/// <summary>PID: 1016 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int totaldecodertx_1016 = 1016;
	/// <summary>PID: 1016 | Type: read</summary>
	public const int totaldecodertx = 1016;
	public class Write
	{
		/// <summary>PID: 1051 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int devicemode_1051 = 1051;
		/// <summary>PID: 1051 | Type: write</summary>
		public const int devicemode = 1051;
		/// <summary>PID: 1054 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int autochromaweight_1054 = 1054;
		/// <summary>PID: 1054 | Type: write</summary>
		public const int autochromaweight = 1054;
		/// <summary>PID: 1056 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int losslessmode_1056 = 1056;
		/// <summary>PID: 1056 | Type: write</summary>
		public const int losslessmode = 1056;
		/// <summary>PID: 1058 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int progressionorder_1058 = 1058;
		/// <summary>PID: 1058 | Type: write</summary>
		public const int progressionorder = 1058;
	}
}
public class WriteParameters
{
	/// <summary>PID: 1051  | Type: write | DISCREETS: Decoder = 0, Encoder = 1</summary>
	public System.Object Devicemode {get { return Protocol.GetParameter(1051); }set { Protocol.SetParameter(1051, value); }}
	/// <summary>PID: 1054  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Autochromaweight {get { return Protocol.GetParameter(1054); }set { Protocol.SetParameter(1054, value); }}
	/// <summary>PID: 1056  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Losslessmode {get { return Protocol.GetParameter(1056); }set { Protocol.SetParameter(1056, value); }}
	/// <summary>PID: 1058  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Progressionorder {get { return Protocol.GetParameter(1058); }set { Protocol.SetParameter(1058, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Fixedzerovalue_1 { get; set; }
	object Fixedzerovalue { get; set; }
	object Placeholdernotavailablevalue_2 { get; set; }
	object Placeholdernotavailablevalue { get; set; }
	object Fixedonevalue__fixed { get; set; }
	object Chromaweightdefaultvalue__fixed { get; set; }
	object Devicemode_1001 { get; set; }
	object Devicemode { get; set; }
	object Encodercurrentcompressedbitrate_1003 { get; set; }
	object Encodercurrentcompressedbitrate { get; set; }
	object Autochromaweight_1004 { get; set; }
	object Autochromaweight { get; set; }
	object Chromaweight_1005 { get; set; }
	object Chromaweight { get; set; }
	object Losslessmode_1006 { get; set; }
	object Losslessmode { get; set; }
	object Decodercurrentcompressedbitrate_1007 { get; set; }
	object Decodercurrentcompressedbitrate { get; set; }
	object Progressionorder_1008 { get; set; }
	object Progressionorder { get; set; }
	object Codeblockwidth_1009 { get; set; }
	object Codeblockwidth { get; set; }
	object Codeblockheight_1010 { get; set; }
	object Codeblockheight { get; set; }
	object Totalencodertx_1015 { get; set; }
	object Totalencodertx { get; set; }
	object Totaldecodertx_1016 { get; set; }
	object Totaldecodertx { get; set; }
	object Devicemode_1051 { get; set; }
	object Autochromaweight_1054 { get; set; }
	object Losslessmode_1056 { get; set; }
	object Progressionorder_1058 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fixedzerovalue_1 {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 1  | Type: read</summary>
	public System.Object Fixedzerovalue {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 2  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Placeholdernotavailablevalue_2 {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 2  | Type: read</summary>
	public System.Object Placeholdernotavailablevalue {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 3  | Type: fixed</summary>
	public System.Object Fixedonevalue__fixed {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 4  | Type: fixed</summary>
	public System.Object Chromaweightdefaultvalue__fixed {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 1001  | Type: read | DISCREETS: Decoder = 0, Encoder = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Devicemode_1001 {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1001  | Type: read | DISCREETS: Decoder = 0, Encoder = 1</summary>
	public System.Object Devicemode {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1003  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encodercurrentcompressedbitrate_1003 {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1003  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encodercurrentcompressedbitrate {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1, Not Reachable = -2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Autochromaweight_1004 {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1, Not Reachable = -2</summary>
	public System.Object Autochromaweight {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1005  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweight_1005 {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1005  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Chromaweight {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1006  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmode_1006 {get { return GetParameter(1006); }set { SetParameter(1006, value); }}
	/// <summary>PID: 1006  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Losslessmode {get { return GetParameter(1006); }set { SetParameter(1006, value); }}
	/// <summary>PID: 1007  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercurrentcompressedbitrate_1007 {get { return GetParameter(1007); }set { SetParameter(1007, value); }}
	/// <summary>PID: 1007  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercurrentcompressedbitrate {get { return GetParameter(1007); }set { SetParameter(1007, value); }}
	/// <summary>PID: 1008  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_1008 {get { return GetParameter(1008); }set { SetParameter(1008, value); }}
	/// <summary>PID: 1008  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Progressionorder {get { return GetParameter(1008); }set { SetParameter(1008, value); }}
	/// <summary>PID: 1009  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockwidth_1009 {get { return GetParameter(1009); }set { SetParameter(1009, value); }}
	/// <summary>PID: 1009  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Codeblockwidth {get { return GetParameter(1009); }set { SetParameter(1009, value); }}
	/// <summary>PID: 1010  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockheight_1010 {get { return GetParameter(1010); }set { SetParameter(1010, value); }}
	/// <summary>PID: 1010  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Codeblockheight {get { return GetParameter(1010); }set { SetParameter(1010, value); }}
	/// <summary>PID: 1015  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Totalencodertx_1015 {get { return GetParameter(1015); }set { SetParameter(1015, value); }}
	/// <summary>PID: 1015  | Type: read</summary>
	public System.Object Totalencodertx {get { return GetParameter(1015); }set { SetParameter(1015, value); }}
	/// <summary>PID: 1016  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Totaldecodertx_1016 {get { return GetParameter(1016); }set { SetParameter(1016, value); }}
	/// <summary>PID: 1016  | Type: read</summary>
	public System.Object Totaldecodertx {get { return GetParameter(1016); }set { SetParameter(1016, value); }}
	/// <summary>PID: 1051  | Type: write | DISCREETS: Decoder = 0, Encoder = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Devicemode_1051 {get { return GetParameter(1051); }set { SetParameter(1051, value); }}
	/// <summary>PID: 1054  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Autochromaweight_1054 {get { return GetParameter(1054); }set { SetParameter(1054, value); }}
	/// <summary>PID: 1056  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmode_1056 {get { return GetParameter(1056); }set { SetParameter(1056, value); }}
	/// <summary>PID: 1058  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_1058 {get { return GetParameter(1058); }set { SetParameter(1058, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
